// <auto-generated />
using System;
using ITAssetManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITAssetManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("department_code");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("longtext")
                        .HasColumnName("department_name");

                    b.Property<string>("DeploymentName")
                        .HasColumnType("longtext")
                        .HasColumnName("deployment_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsKittingDepartment")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_kitting_department");

                    b.Property<bool>("OverallDeployment")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("overall_deployment");

                    b.Property<int?>("ParentDepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_department_id");

                    b.Property<string>("TopDeploymentName")
                        .HasColumnType("longtext")
                        .HasColumnName("top_deployment_name");

                    b.HasKey("DepartmentId");

                    b.HasIndex("ParentDepartmentId");

                    b.ToTable("DEPARTMENT", (string)null);
                });

            modelBuilder.Entity("ITAssetManagement.Models.AssetCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("longtext")
                        .HasColumnName("category_name");

                    b.HasKey("CategoryId");

                    b.ToTable("ASSET_CATEGORY");
                });

            modelBuilder.Entity("ITAssetManagement.Models.AssetLocation", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("LocationName")
                        .HasColumnType("longtext")
                        .HasColumnName("location_name");

                    b.HasKey("LocationId");

                    b.ToTable("ASSET_LOCATION");
                });

            modelBuilder.Entity("ITAssetManagement.Models.AssetStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .HasColumnType("longtext")
                        .HasColumnName("status_name");

                    b.HasKey("StatusId");

                    b.ToTable("ASSET_STATUS");
                });

            modelBuilder.Entity("ITAssetManagement.Models.DepartmentRepresentative", b =>
                {
                    b.Property<int>("RepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rep_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RepId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<bool>("IsPrimaryAdmin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_primary_admin");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("RepId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("DEPARTMENT_REPRESENTATIVE");
                });

            modelBuilder.Entity("ITAssetManagement.Models.ITAsset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AssetId"));

                    b.Property<string>("AssetControlNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("asset_control_number");

                    b.Property<int?>("AssetManagerId")
                        .HasColumnType("int")
                        .HasColumnName("asset_manager_id");

                    b.Property<string>("AssetName")
                        .HasColumnType("longtext")
                        .HasColumnName("asset_name");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<int?>("InventoryId")
                        .HasColumnType("int")
                        .HasColumnName("inventory_id");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("longtext")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .HasColumnType("longtext")
                        .HasColumnName("model");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("purchase_date");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("serial_number");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("updated_by");

                    b.Property<int?>("UserCreatedId")
                        .HasColumnType("int")
                        .HasColumnName("user_created_id");

                    b.Property<int?>("UserUsedId")
                        .HasColumnType("int")
                        .HasColumnName("user_used_id");

                    b.Property<DateTime?>("WarrantyExpiry")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("warranty_expiry");

                    b.HasKey("AssetId");

                    b.HasIndex("AssetManagerId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("LocationId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserCreatedId");

                    b.HasIndex("UserUsedId");

                    b.ToTable("IT_ASSET", (string)null);
                });

            modelBuilder.Entity("ITAssetManagement.Models.InventoryHistory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("inventory_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<DateTime>("InventoryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("inventory_date");

                    b.Property<int>("InventoryDepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("inventory_department_id");

                    b.Property<int>("InventoryImplementer")
                        .HasColumnType("int")
                        .HasColumnName("inventory_implementer");

                    b.Property<string>("InventoryStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("inventory_status");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("remarks");

                    b.HasKey("InventoryId");

                    b.HasIndex("InventoryDepartmentId");

                    b.HasIndex("InventoryImplementer");

                    b.ToTable("INVENTORY_HISTORY");
                });

            modelBuilder.Entity("ITAssetManagement.Models.License", b =>
                {
                    b.Property<int>("LicenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("license_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LicenseId"));

                    b.Property<bool>("AcademicFlag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("academic_flag");

                    b.Property<string>("CountingMethod")
                        .HasColumnType("longtext")
                        .HasColumnName("counting_method");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DisposalDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("disposal_date");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiry_date");

                    b.Property<string>("InstallationName")
                        .HasColumnType("longtext")
                        .HasColumnName("installation_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<int?>("LicenseCount")
                        .HasColumnType("int")
                        .HasColumnName("license_count");

                    b.Property<string>("LicenseFormat")
                        .HasColumnType("longtext")
                        .HasColumnName("license_format");

                    b.Property<string>("LicenseKey")
                        .HasColumnType("longtext")
                        .HasColumnName("license_key");

                    b.Property<string>("LicenseManagementNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("license_management_number");

                    b.Property<string>("LicenseStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("license_status");

                    b.Property<string>("LicenseType")
                        .HasColumnType("longtext")
                        .HasColumnName("license_type");

                    b.Property<int?>("ManagementDepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("management_department_id");

                    b.Property<int?>("ManagerUserId")
                        .HasColumnType("int")
                        .HasColumnName("manager_user_id");

                    b.Property<int>("NumberAvailable")
                        .HasColumnType("int")
                        .HasColumnName("number_available");

                    b.Property<int>("NumberOfLicenses")
                        .HasColumnType("int")
                        .HasColumnName("number_of_licenses");

                    b.Property<int?>("ParentLicenseId")
                        .HasColumnType("int")
                        .HasColumnName("parent_license_id");

                    b.Property<string>("PublisherName")
                        .HasColumnType("longtext")
                        .HasColumnName("publisher_name");

                    b.Property<string>("SoftwareType")
                        .HasColumnType("longtext")
                        .HasColumnName("software_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("updated_by");

                    b.HasKey("LicenseId");

                    b.HasIndex("ManagementDepartmentId");

                    b.HasIndex("ManagerUserId");

                    b.HasIndex("ParentLicenseId");

                    b.ToTable("LICENSE", (string)null);
                });

            modelBuilder.Entity("ITAssetManagement.Models.LicenseInventoryHistory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("inventory_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("InventoryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("inventory_date");

                    b.Property<string>("InventoryStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("inventory_status");

                    b.Property<int?>("InventoryTakerId")
                        .HasColumnType("int")
                        .HasColumnName("inventory_taker_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<int>("LicenseId")
                        .HasColumnType("int")
                        .HasColumnName("license_id");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext")
                        .HasColumnName("remarks");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("updated_by");

                    b.HasKey("InventoryId");

                    b.HasIndex("InventoryTakerId");

                    b.HasIndex("LicenseId");

                    b.ToTable("LICENSE_INVENTORY_HISTORY", (string)null);
                });

            modelBuilder.Entity("ITAssetManagement.Models.PermissionRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .HasColumnType("longtext")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.ToTable("PERMISSION_ROLE", (string)null);
                });

            modelBuilder.Entity("ITAssetManagement.Models.Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("approved_at");

                    b.Property<int?>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<int?>("FirstApproverId")
                        .HasColumnType("int")
                        .HasColumnName("first_approver_id");

                    b.Property<string>("RejectReason")
                        .HasColumnType("longtext")
                        .HasColumnName("reject_reason");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("rejected_at");

                    b.Property<string>("RequestData")
                        .HasColumnType("longtext")
                        .HasColumnName("request_data");

                    b.Property<string>("RequestDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("request_description");

                    b.Property<int>("RequestTypeId")
                        .HasColumnType("int")
                        .HasColumnName("request_type_id");

                    b.Property<int?>("SecondApproverId")
                        .HasColumnType("int")
                        .HasColumnName("second_approver_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<int?>("TargetDiv")
                        .HasColumnType("int")
                        .HasColumnName("target_div");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("updated_by");

                    b.Property<int>("UserCreatedId")
                        .HasColumnType("int")
                        .HasColumnName("user_created_id");

                    b.HasKey("RequestId");

                    b.HasIndex("AssetId");

                    b.HasIndex("RequestTypeId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserCreatedId");

                    b.ToTable("REQUEST");
                });

            modelBuilder.Entity("ITAssetManagement.Models.RequestDetail", b =>
                {
                    b.Property<int>("RequestDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detail_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RequestDetailId"));

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("field_name");

                    b.Property<string>("NewValue")
                        .HasColumnType("longtext")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("longtext")
                        .HasColumnName("old_value");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.HasKey("RequestDetailId");

                    b.HasIndex("RequestId");

                    b.ToTable("REQUEST_DETAIL");
                });

            modelBuilder.Entity("ITAssetManagement.Models.RequestType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type_name");

                    b.HasKey("TypeId");

                    b.ToTable("REQUEST_TYPE");
                });

            modelBuilder.Entity("ITAssetManagement.Models.Software", b =>
                {
                    b.Property<int>("SoftwareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("software_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SoftwareId"));

                    b.Property<string>("AssetControlNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("asset_control_number");

                    b.Property<int?>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<int?>("InstalledBy")
                        .HasColumnType("int")
                        .HasColumnName("installed_by");

                    b.Property<DateTime>("InstalledDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("installed_date");

                    b.Property<int?>("LicenseId")
                        .HasColumnType("int")
                        .HasColumnName("license_id");

                    b.Property<string>("LicenseType")
                        .HasColumnType("longtext")
                        .HasColumnName("license_type");

                    b.Property<string>("SoftwareName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("software_name");

                    b.Property<string>("SoftwareType")
                        .HasColumnType("longtext")
                        .HasColumnName("software_type");

                    b.Property<string>("SoftwareVersion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("software_version");

                    b.Property<int?>("VendorId")
                        .HasColumnType("int")
                        .HasColumnName("vendor_id");

                    b.HasKey("SoftwareId");

                    b.HasIndex("AssetId");

                    b.HasIndex("InstalledBy");

                    b.ToTable("SOFTWARE");
                });

            modelBuilder.Entity("ITAssetManagement.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("AuditorFlag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("auditor_flag");

                    b.Property<string>("ConsoleLoginId")
                        .HasColumnType("longtext")
                        .HasColumnName("console_login_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<int?>("PrimaryDepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("primary_department_id");

                    b.Property<string>("ResetOtp")
                        .HasColumnType("longtext")
                        .HasColumnName("reset_otp");

                    b.Property<DateTime?>("ResetOtpExpiry")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reset_otp_expiry");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("SystemLoginId")
                        .HasColumnType("longtext")
                        .HasColumnName("system_login_id");

                    b.Property<string>("UserCode")
                        .HasColumnType("longtext")
                        .HasColumnName("user_code");

                    b.Property<string>("Username")
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.Property<string>("UsernameAlphabet")
                        .HasColumnType("longtext")
                        .HasColumnName("username_alphabet");

                    b.Property<string>("UsernameKana")
                        .HasColumnType("longtext")
                        .HasColumnName("username_kana");

                    b.HasKey("UserId");

                    b.HasIndex("PrimaryDepartmentId");

                    b.HasIndex("RoleId");

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("ITAssetManagement.Models.UserItem", b =>
                {
                    b.Property<int>("UserItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_item_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserItemId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("ItemKey")
                        .HasColumnType("longtext")
                        .HasColumnName("item_key");

                    b.Property<string>("ItemValue")
                        .HasColumnType("longtext")
                        .HasColumnName("item_value");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("UserItemId");

                    b.HasIndex("UserId");

                    b.ToTable("USER_ITEMS");
                });

            modelBuilder.Entity("ITAssetManagement.Models.UserPermission", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<bool>("CanAdmin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_admin");

                    b.Property<bool>("CanApprove")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_approve");

                    b.Property<bool>("CanRequest")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_request");

                    b.Property<bool>("CanView")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_view");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("USER_PERMISSION", (string)null);
                });

            modelBuilder.Entity("RequestApproval", b =>
                {
                    b.Property<int>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("approval_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ApprovalId"));

                    b.Property<int>("ApprovalLevel")
                        .HasColumnType("int")
                        .HasColumnName("approval_level");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("approved_at");

                    b.Property<int>("ApproverId")
                        .HasColumnType("int")
                        .HasColumnName("approver_id");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.HasKey("ApprovalId");

                    b.HasIndex("RequestId");

                    b.ToTable("request_approval");
                });

            modelBuilder.Entity("RequestAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("RequestId");

                    b.ToTable("REQUEST_ASSET");
                });

            modelBuilder.Entity("RequestHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("history_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("action");

                    b.Property<DateTime>("ActionAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("action_at");

                    b.Property<string>("ActionBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("action_by");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext")
                        .HasColumnName("remarks");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<int?>("UserCreatedId")
                        .HasColumnType("int")
                        .HasColumnName("user_created_id");

                    b.HasKey("HistoryId");

                    b.ToTable("request_history");
                });

            modelBuilder.Entity("RequestStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status_name");

                    b.HasKey("StatusId");

                    b.ToTable("REQUEST_STATUS");
                });

            modelBuilder.Entity("Department", b =>
                {
                    b.HasOne("Department", "ParentDepartment")
                        .WithMany("ChildDepartments")
                        .HasForeignKey("ParentDepartmentId");

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("ITAssetManagement.Models.DepartmentRepresentative", b =>
                {
                    b.HasOne("Department", "Department")
                        .WithMany("Representatives")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetManagement.Models.PermissionRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetManagement.Models.User", "User")
                        .WithMany("DepartmentRepresentatives")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ITAssetManagement.Models.ITAsset", b =>
                {
                    b.HasOne("ITAssetManagement.Models.User", "AssetManager")
                        .WithMany()
                        .HasForeignKey("AssetManagerId");

                    b.HasOne("ITAssetManagement.Models.AssetCategory", "Category")
                        .WithMany("Assets")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("ITAssetManagement.Models.InventoryHistory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId");

                    b.HasOne("ITAssetManagement.Models.AssetLocation", "Location")
                        .WithMany("Assets")
                        .HasForeignKey("LocationId");

                    b.HasOne("ITAssetManagement.Models.AssetStatus", "Status")
                        .WithMany("Assets")
                        .HasForeignKey("StatusId");

                    b.HasOne("ITAssetManagement.Models.User", "UserCreated")
                        .WithMany()
                        .HasForeignKey("UserCreatedId");

                    b.HasOne("ITAssetManagement.Models.User", "UserUsed")
                        .WithMany()
                        .HasForeignKey("UserUsedId");

                    b.Navigation("AssetManager");

                    b.Navigation("Category");

                    b.Navigation("Department");

                    b.Navigation("Inventory");

                    b.Navigation("Location");

                    b.Navigation("Status");

                    b.Navigation("UserCreated");

                    b.Navigation("UserUsed");
                });

            modelBuilder.Entity("ITAssetManagement.Models.InventoryHistory", b =>
                {
                    b.HasOne("Department", "InventoryDepartment")
                        .WithMany()
                        .HasForeignKey("InventoryDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetManagement.Models.User", "InventoryImplementerNavigation")
                        .WithMany()
                        .HasForeignKey("InventoryImplementer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryDepartment");

                    b.Navigation("InventoryImplementerNavigation");
                });

            modelBuilder.Entity("ITAssetManagement.Models.License", b =>
                {
                    b.HasOne("Department", "ManagementDepartment")
                        .WithMany()
                        .HasForeignKey("ManagementDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ITAssetManagement.Models.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ITAssetManagement.Models.License", "ParentLicense")
                        .WithMany("ChildLicenses")
                        .HasForeignKey("ParentLicenseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ManagementDepartment");

                    b.Navigation("Manager");

                    b.Navigation("ParentLicense");
                });

            modelBuilder.Entity("ITAssetManagement.Models.LicenseInventoryHistory", b =>
                {
                    b.HasOne("ITAssetManagement.Models.User", "InventoryTaker")
                        .WithMany()
                        .HasForeignKey("InventoryTakerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ITAssetManagement.Models.License", "License")
                        .WithMany("InventoryHistories")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryTaker");

                    b.Navigation("License");
                });

            modelBuilder.Entity("ITAssetManagement.Models.Request", b =>
                {
                    b.HasOne("ITAssetManagement.Models.ITAsset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId");

                    b.HasOne("ITAssetManagement.Models.RequestType", "RequestType")
                        .WithMany()
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequestStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetManagement.Models.User", "UserCreated")
                        .WithMany()
                        .HasForeignKey("UserCreatedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("RequestType");

                    b.Navigation("Status");

                    b.Navigation("UserCreated");
                });

            modelBuilder.Entity("ITAssetManagement.Models.RequestDetail", b =>
                {
                    b.HasOne("ITAssetManagement.Models.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ITAssetManagement.Models.Software", b =>
                {
                    b.HasOne("ITAssetManagement.Models.ITAsset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId");

                    b.HasOne("ITAssetManagement.Models.User", "InstalledByUser")
                        .WithMany()
                        .HasForeignKey("InstalledBy");

                    b.Navigation("Asset");

                    b.Navigation("InstalledByUser");
                });

            modelBuilder.Entity("ITAssetManagement.Models.User", b =>
                {
                    b.HasOne("Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("PrimaryDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ITAssetManagement.Models.PermissionRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ITAssetManagement.Models.UserItem", b =>
                {
                    b.HasOne("ITAssetManagement.Models.User", "User")
                        .WithMany("UserItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ITAssetManagement.Models.UserPermission", b =>
                {
                    b.HasOne("ITAssetManagement.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("ITAssetManagement.Models.UserPermission", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RequestApproval", b =>
                {
                    b.HasOne("ITAssetManagement.Models.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("RequestAsset", b =>
                {
                    b.HasOne("ITAssetManagement.Models.ITAsset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetManagement.Models.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Department", b =>
                {
                    b.Navigation("ChildDepartments");

                    b.Navigation("Representatives");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ITAssetManagement.Models.AssetCategory", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("ITAssetManagement.Models.AssetLocation", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("ITAssetManagement.Models.AssetStatus", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("ITAssetManagement.Models.License", b =>
                {
                    b.Navigation("ChildLicenses");

                    b.Navigation("InventoryHistories");
                });

            modelBuilder.Entity("ITAssetManagement.Models.PermissionRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ITAssetManagement.Models.User", b =>
                {
                    b.Navigation("DepartmentRepresentatives");

                    b.Navigation("UserItems");
                });
#pragma warning restore 612, 618
        }
    }
}
